---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rfintext

<!-- badges: start -->
<!-- badges: end -->

This package contains data set `aspol` created from Finnish
housing policy documents.

## Installation

You can install the development version of rfintext like so:

``` r
# install.packages("devtools")
devtools::install_github("StranMax/rfintext")
```


```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(tidyverse)
```

Number of documents currently `r length(unique(aspol$kunta))`

Example from dataset, sentence nro 43 from Espoo document:

```{r, R.options = list(width = 10000), rows.print=26}
aspol |> filter(kunta == "Espoo", sent == 43)
```

```{r, R.options = list(width = 10000), rows.print=10}
aspol |>
  dplyr::filter(UPOSTAG %in% c("NOUN", "VERB", "ADJ", "ADV")) |>
  dplyr::count(LEMMA, UPOSTAG, sort = TRUE)
```

```{r}
aspol |>
  group_by(LEMMA) |>
  summarise(taivutusmuodot = length(unique(FORM))) |>
  arrange(desc(taivutusmuodot))
```

```{r , R.options = list(width = 10000), rows.print=81}
aspol |>
  filter(LEMMA == "asunto") |>
  count(FORM, FEATS, sort = TRUE)
```

```{r}
aspol |>
  group_by(FORM) |>
  summarise(perusmuoto = length(unique(UPOSTAG))) |>
  arrange(desc(perusmuoto))
```

```{r , R.options = list(width = 10000), rows.print=81}
aspol |>
  filter(LEMMA == "olla") |>
  count(FORM, LEMMA, UPOSTAG, FEATS, sort = TRUE)
```

