---
title: "2 Document term matrix"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Analysis expects input data to be in numerical form.

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(tidytext)
library(dplyr)
library(quanteda)
```

```{r, include=FALSE}
quanteda_options(print_dfm_max_ndoc = 20, print_dfm_max_nfeat = 20)
```

Pre processing aspol corpus and calculating document term count (dtc)

```{r, message=FALSE, R.options = list(width = 10000, pillar.print_max = 20, pillar.print_min = 20)}
aspol |>
  preprocess_corpus(kunta) |>
  count(kunta, LEMMA, name = "dtc")
```

Converting original corpus to document term matrix.

```{r, message=FALSE, R.options = list(width = 10000)}
dtm <- aspol |>
  preprocess_corpus(kunta) |>
  count(kunta, LEMMA, name = "dtc") |>
  cast_dfm(document = kunta, term = LEMMA, value = dtc)  # quanteda format
  # cast_dtm(document = kunta, term = LEMMA, value = dtc)  # tm format
dtm
```

It is possible to convert from one format to another with `quanteda::convert()` 
function. For example some functions require data to be in `tm` format.

```{r}
dtm |>
  quanteda::convert(to = "tm")
```

