---
title: "3 LDA"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(rfinstats)
library(quanteda)
library(topicmodels)
library(tidytext)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
tf
```

```{r}
topfeatures(tc)
```

```{r}
topfeatures(tf)
```

```{r}
topfeatures(tf_idf)
```

```{r}
named_vec2df <- function(vec) {
  nms <- names(vec)
  vls <- vec
  # var = deparse(substitute(vec))
  var = enexpr(vec)
  tibble(term = nms, value = vls, type = var)
}
```

```{r}
bind_rows(
lapply(list(tc, tf, tf_idf), function(x) {
  # enexpr(x)
  named_vec2df(topfeatures(x))
})
)
```

```{r}
k_size = 3L
```

Can't convert `tf` or `tf_idf` to tm format. `LDA()` raises error. Conversion
calculates term frequency automatically? Therefore calculating term frequency of 
term frequencies?

```{r}
aspol_lda <- LDA(convert(tc, to = "tm"), k = k_size, control = list(seed = 1234))
```

```{r}
aspol_lda
```

```{r}
aspol_topics <- tidy(aspol_lda, matrix = "beta")
```

```{r}
aspol_top_terms <- aspol_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

aspol_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

```{r}
beta_wide <- aspol_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  pivot_wider(names_from = topic, values_from = beta) %>% 
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio_1_2 = log2(topic2 / topic1),
         log_ratio_2_3 = log2(topic3 / topic2),
         log_ratio_1_3 = log2(topic3 / topic1))

beta_wide
```

```{r}
plot_log_ratios <- function(log_ratio) {
  beta_wide |>
  arrange({{log_ratio}}) |>
  mutate(term = reorder(term, {{log_ratio}})) |>
  slice(1:10, (n()-10):n()) |>
ggplot() +
  geom_col(aes(x = {{log_ratio}}, y = term))
}
```

```{r}
plot_log_ratios(log_ratio_1_2)
```

```{r}
plot_log_ratios(log_ratio_2_3)
```

```{r}
plot_log_ratios(log_ratio_1_3)
```

```{r}
aspol_documents <- tidy(aspol_lda, matrix = "gamma")
```

```{r}
aspol_documents |>
  slice_max(order_by = gamma, n = 1, by = document) |>
  left_join(taantuvat, by = join_by(document == kunta)) |>
  count(topic, luokka, sort = TRUE) |>
  ggplot() +
  geom_col(aes(x = luokka, y = n, fill = topic))
```

