---
title: "3 LDA parameter tuning"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Topic modeling with latent Dirichlet allocation (LDA). Finding optimal k-parameter.
Using coherence score as a value of goodness.

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(quanteda)
library(topicmodels)
library(topicdoc)
library(dplyr)
library(ggplot2)
library(doParallel)
library(parallel)
library(foreach)
```

```{r}
dtm <- aspol |>
  preprocess_corpus() |>
  corpus_to_dtm(kunta, LEMMA)
```

```{r}
topfeatures(dtm)
```

```{r}
get_coherence <- function(k) {
  lda <- topicmodels::LDA(quanteda::convert(dtm, to = "tm"), k = k, control = list(seed = 1234))
  coherence <- mean(topicdoc::topic_coherence(lda, dtm))
  c(k, coherence)
}
```

```{r}
initialize_cluster <- function(...) {
  no_cores <- parallel::detectCores(logical = FALSE)
  cl <- parallel::makeCluster(no_cores-1, type='PSOCK')  # Works on windows
  doParallel::registerDoParallel(cl)
  clusterExport(cl,list(...))  # Exported objects to cluster
  return(cl)
}
```


```{r}
cl <- initialize_cluster('get_coherence', 'dtm')
k_values <- seq(20, 200, by = 10)
print(Sys.time())
results <- foreach(i = k_values, .combine = 'rbind', .inorder=FALSE) %dopar% {
    get_coherence(i)
}
parallel::stopCluster(cl)
print(Sys.time())
```

```{r}
plot_coherence <- function(mx) {
  ggplot(as.data.frame(mx)) +
    geom_line(aes(x = V1, y = V2)) +
    labs(x = "k", y = "Avg coherence")
}
```


```{r}
plot_coherence(results)
```


```{r}
cl <- initialize_cluster('get_coherence', 'dtm')
k_values <- seq(5, 40, by = 5)
print(Sys.time())
results2 <- foreach(i = k_values, .combine = 'rbind', .inorder=FALSE) %dopar% {
    get_coherence(i)
}
parallel::stopCluster(cl)
print(Sys.time())
```

```{r}
plot_coherence(results2)
```

```{r}
cl <- initialize_cluster('get_coherence', 'dtm')
k_values <- seq(5, 20, by = 1)
print(Sys.time())
results3 <- foreach(i = k_values, .combine = 'rbind', .inorder=FALSE) %dopar% {
    get_coherence(i)
}
parallel::stopCluster(cl)
print(Sys.time())
```

```{r}
plot_coherence(results3)
```
Therefore optimal value for key would be either 6 or 15. 

