---
title: "3 Sanapilvet"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
# devtools::install_github("StranMax/rfinstats")
library(rfinstats)
library(dplyr)
library(sf)
library(tidytext)
library(ggplot2)
library(stringr)
library(forcats)
library(ggwordcloud)
```

```{r}
aspol <- left_join(aspol, taantuvat)
```


```{r}
# suodatettavat <- c("✓", "", "x", "X", "@", "bostad", "\\.")
# pattern <- str_c(suodatettavat, collapse = "|")
aspol <- aspol |> filter(
  #!str_detect(LEMMA, pattern),
  !str_detect(FEATS, "Foreign=Yes"),
  nchar(LEMMA) > 2
  )

noun_adj <- aspol |> filter(UPOSTAG %in% c("NOUN", "ADJ"))
verb_adv <- aspol |> filter(UPOSTAG %in% c("VERB", "ADV"))
```

```{r}
tf_noun_adj_luokka <- noun_adj |>
  filter(!is.na(luokka)) |>
  count(luokka, LEMMA, sort = TRUE)

tf_noun_adj_luokka
```

```{r}
noun_adj_sum_per_luokka <-  tf_noun_adj_luokka |>
  group_by(luokka) |>
  summarise(total = sum(n))

noun_adj_sum_per_luokka
```

```{r, message=FALSE}
tf_idf_noun_adj <-  tf_noun_adj_luokka |>
  left_join(noun_adj_sum_per_luokka) |>
  bind_tf_idf(LEMMA, luokka, n)
```

```{r}
tf_idf_noun_adj %>%
  select(-total) %>%
  arrange(desc(tf_idf))
```

```{r, fig.width=8.27, fig.height=5.83, fig.fullwidth=TRUE}
tf_idf_noun_adj |>
  slice_max(tf_idf, n = 30, by = luokka) |>
ggplot(aes(label = LEMMA, size = tf_idf, colour = luokka)) +
  geom_text_wordcloud_area(rm_outside = TRUE, shape = "square", use_richtext = FALSE) +
  scale_size_area(max_size = 30) +
  theme_minimal() +
  facet_wrap(~luokka, nrow = 2)
```

```{r}
tf_verb_adv_luokka <- verb_adv |>
  filter(!is.na(luokka)) |>
  count(luokka, LEMMA, sort = TRUE)

tf_verb_adv_luokka
```

```{r}
verb_adv_sum_per_luokka <-  tf_verb_adv_luokka |>
  group_by(luokka) |>
  summarise(total = sum(n))

verb_adv_sum_per_luokka
```

```{r, message=FALSE}
tf_idf_verb_adv <-  tf_verb_adv_luokka |>
  left_join(verb_adv_sum_per_luokka) |>
  bind_tf_idf(LEMMA, luokka, n)
```

```{r}
tf_idf_verb_adv %>%
  select(-total) %>%
  arrange(desc(tf_idf))
```

```{r, fig.width=8.27, fig.height=5.83, fig.fullwidth=TRUE}
tf_idf_verb_adv |>
  slice_max(tf_idf, n = 30, by = luokka) |>
ggplot(aes(label = LEMMA, size = tf_idf, colour = luokka)) +
  geom_text_wordcloud_area(rm_outside = TRUE, shape = "square", use_richtext = FALSE) +
  scale_size_area(max_size = 30) +
  theme_minimal() +
  facet_wrap(~luokka, nrow = 2)
```


