---
title: "3 Topic modeling"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Topic modeling with latent Dirichlet allocation (LDA). Finding optimal k-parameter.
Using coherence score as a value of goodness.

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(rfinstats)
library(quanteda)
library(tidytext)
library(topicmodels)
library(topicdoc)
library(dplyr)
library(tidyr)
library(ggplot2)
# library(DT)
library(kableExtra)
library(doFuture)
plan(multisession, workers = availableCores(logical = FALSE) - 1)
```

```{r, include=FALSE}
quanteda_options(print_dfm_max_ndoc = 20, print_dfm_max_nfeat = 20)
```

```{r, message=FALSE, R.options = list(width = 10000)}
dtm <- aspol |>
  preprocess_corpus() |>
  corpus_to_dtm(kunta, LEMMA)
dtm
```

```{r, R.options=list(width=10000)}
topfeatures(dtm)
```

LDA needs one parameter `k`. Finding optimal values by evaluating coherence score.


```{r, warning=FALSE}
k_values <- c(seq(2, 70, by = 1))
system.time(
  model_coherence <- foreach(k = k_values, .combine = 'rbind', .inorder = FALSE) %dofuture% {
    lda <- topicmodels::LDA(quanteda::convert(dtm, to = "tm"), k = k, control = list(seed = 1234))
    mean_coherence <- mean(topicdoc::topic_coherence(lda, dtm))
    data_frame(k = k, mean_coherence = mean_coherence)
  }
)
```

```{r}
# save(model_coherence, file = "./extdata/model_coherence.rda")  # Does not work!!??
# usethis::use_data(model_coherence)
```

```{r}
p <- model_coherence |>
  ggplot(aes(x = k, y = mean_coherence)) +
  geom_line()
p
```

Visually selecting potentially best k values
```{r}
optimal_k <- c(5, 15, 18, 21)
```


```{r}
p +
  geom_vline(xintercept = optimal_k, linetype='dashed', color=c('red')) +
  lapply(optimal_k, function(x) {geom_text(aes(x=x+1, label=x, y=-5), colour="red", angle=90)}) +
  labs(title = "Optimal k values")
```

Highest coherence values: `r optimal_k`

```{r, warning=FALSE}
lda_models <- foreach(k = optimal_k) %dofuture% {
  topicmodels::LDA(quanteda::convert(dtm, to = "tm"), k = k, control = list(seed = 1234))
}
names(lda_models) <- paste0("k_", optimal_k)
```

```{r, R.options=list(width = 10000, pillar.print_max = 25, pillar.print_min = 25)}
beta_matrix <- bind_rows(
  lapply(lda_models, function(x) {
    tidytext::tidy(x, matrix = "beta")
  }), 
  .id = "model")
beta_matrix
```

```{r}
topic_congruence <- beta_matrix |>
  pivot_wider(values_from = beta, names_from = topic) |>
  rename_with(~paste0("Topic_", .), where(is.numeric)) |>
  select(-term)
topic_congruence
```

```{r}
k_5_k_15 <-  cor(topic_congruence[topic_congruence$model=="k_5", 2:6], topic_congruence[topic_congruence$model=="k_15", 2:16])
k_5_k_18 <-  cor(topic_congruence[topic_congruence$model=="k_5", 2:6], topic_congruence[topic_congruence$model=="k_18", 2:19])
k_5_k_21 <-  cor(topic_congruence[topic_congruence$model=="k_5", 2:6], topic_congruence[topic_congruence$model=="k_21", 2:22])
k_15_k_18 <-  cor(topic_congruence[topic_congruence$model=="k_15", 2:16], topic_congruence[topic_congruence$model=="k_18", 2:19])
k_15_k_21 <-  cor(topic_congruence[topic_congruence$model=="k_15", 2:16], topic_congruence[topic_congruence$model=="k_21", 2:22])
k_18_k_21 <-  cor(topic_congruence[topic_congruence$model=="k_18", 2:19], topic_congruence[topic_congruence$model=="k_21", 2:22])
topic_correlation <- list(k_5_k_15, k_5_k_18, k_5_k_21, k_15_k_18, k_15_k_21, k_18_k_21)
names(topic_correlation) <-  c("k_5_vs_k_15", "k_5_vs_k_18", "k_5_vs_k_21", "k_15_vs_k_18", "k_15_vs_k_21", "k_18_vs_k_21")
```

```{r}
for (i in seq_along(topic_correlation)) {
  print(
    pivot_longer(as_tibble(topic_correlation[[i]], rownames = "model1"), !model1, names_to = "model2", values_to = "correlation") |>
      mutate(topic_nro1 = as.integer(stringr::str_extract(model1, "\\d+")),
             topic_nro2 = as.integer(stringr::str_extract(model2, "\\d+"))) |>
      ggplot(aes(x = forcats::fct_reorder(model1, topic_nro1, sum), y = forcats::fct_reorder(model2, topic_nro2, sum), fill = correlation, label = round(correlation, 2))) +
      geom_tile(show.legend = FALSE) +
      geom_text() +
      theme(axis.text.x = element_text(angle = 90)) +
      labs(subtitle = names(topic_correlation)[i]) +
      scale_fill_viridis_c(option = "A")
    )
}
```


```{r, R.options=list(width = 10000, pillar.print_max = 25, pillar.print_min = 25)}
theta_matrix <- bind_rows(
  lapply(lda_models, function(x) {
    tidytext::tidy(x, matrix = "gamma")
  }),
  .id = "model")
theta_matrix
```

```{r}
topic_prevalence <-  theta_matrix |>
  summarise(mean_gamma = mean(gamma), median_gamma = median(gamma), .by = c(model, topic)) |>
  mutate(gamma = paste0(round(mean_gamma, 2), " (", round(median_gamma, 2), ")")) #|>
  # select(model, topic, gamma) |>
  # tidyr::pivot_wider(names_from =  model, values_from = gamma, values_fill = "")

kbl(topic_prevalence) |>
  kable_styling(fixed_thead = T)
```


```{r}
ggplot(topic_prevalence, aes(x = factor(topic), y = mean_gamma)) +
  geom_col() +
  facet_wrap(~ factor(model, levels =  c("k_5", "k_15", "k_18", "k_21")), scales = "free_x") +
  labs(subtitle = "Topic prevalence")
```

```{r, fig.height=7, fig.width=21}
beta_matrix |>
  filter(model == "k_5") |>
  group_by(topic) |>
  slice_max(beta, n = 25) |>
  mutate(topic = as.factor(topic)) |>
  ggplot(aes(x = beta, y = reorder(term, beta), fill = topic)) +
  geom_col(show.legend = FALSE) +
  scale_fill_viridis_d(option = "A") +
  facet_wrap(~topic, scales = "free", ncol = 3)
```


```{r, R.options=list(width = 10000)}
doc_topics <- lapply(lda_models, function(x) {
  x |>
    tidytext::tidy(matrix = "gamma") |>
    tidytext::cast_dfm(document, topic, gamma)
})
doc_topics
```


```{r}
join_y <- function(df) {
  df |>
    left_join(taantuvat, by = join_by("doc_id" == "kunta")) |>
    filter(!is.na(luokka))
}
```

```{r}
summarise_topics <- function(df, ...) {
  df |>
    mutate(topic = factor(as.integer(topic))) |>
    summarise(...)
}
```


```{r}
plot_topic_mean_prop <- function(df, ...) {
  df |>
    ggplot() +
    geom_point(aes(...))
}
```

```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    summarise_topics(sum_prop = sum(prop), .by = c(luokka, topic)) |>
    plot_topic_mean_prop(x = topic, y = sum_prop, colour = luokka)
}
)
```

```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    summarise_topics(mean_prop = mean(prop), .by = c(luokka, topic)) |>
    plot_topic_mean_prop(x = topic, y = mean_prop, colour = luokka)
}
)
```


```{r}
taantuvat |>
  filter(kunta %in% unique(aspol$kunta)) |>
  mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva")) |>
  count(luokka, sort = TRUE)
```

```{r}
# purrr::imap(doc_topics, function(x, name) { 
#   x |>
#     gather_topic_prob() |>
#     join_y() |>
#     select(doc_id, topic, prop, suht_muutos_2010_2022, luokka) |>
#     tidyr::pivot_wider(names_from = topic, values_from = prop) |>
#     rename_with(~ paste0("topic_", .x, recycle0 = TRUE), matches("^[0-9]+$")) |>
#     write.csv(paste0("topic_", name, ".csv"))
# })
```


```{r}
dat <- doc_topics$k_5 |> 
  gather_topic_prob() |>
  join_y() |>
  mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
         topic = factor(as.integer(topic))) |>
  select(topic, prop, luokka)
dat
```

```{r}
for (i in seq_along(unique(dat$topic))) {
  cat("Topic ", i)
  print(
    dat |> filter(topic == i) |>
    ggplot() +
    geom_boxplot(aes(x = luokka, y = prop)) +
      labs(title = paste0("Topic ", i))
    )
  print(
    dat |>
      filter(topic == i) |>
      kruskal.test(luokka ~ prop, data = _)
  )
} 
```


```{r}
doc_topics$k_5 |>
  gather_topic_prob() |>
  join_y() |>
  mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
         topic = factor(as.integer(topic))) |>
  summarise(topic_sum = sum(prop), 
            topic_mean = mean(prop),
            .by = c(luokka, topic)) |>
  kruskal.test(topic_sum ~ luokka)
```

```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
           topic = factor(as.integer(topic))) |>
    summarise(mean_prop = mean(prop), .by = c(luokka, topic)) |>
    tidyr::pivot_wider(names_from = luokka, values_from = mean_prop) |>
    mutate(diff = Kasvava-Taantuva) |>
    ggplot() +
    geom_point(aes(x = topic, y = diff)) +
    ylim(-0.4, 0.4) +
    geom_hline(yintercept = 0)
})
```


```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
           topic = factor(as.integer(topic))) |>
    summarise(topic_sum = sum(prop), 
              topic_mean = mean(prop),
              .by = c(luokka, topic)) |>
    ggplot() +
    geom_tile(aes(x = topic, y = luokka, fill = topic_sum)) +
    scale_fill_viridis_c(option = "A")
}
)
```

```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
           topic = factor(as.integer(topic))) |>
    summarise(topic_sum = sum(prop), 
              topic_mean = mean(prop),
              .by = c(luokka, topic)) |>
    ggplot() +
    geom_tile(aes(x = topic, y = luokka, fill = topic_mean)) +
    scale_fill_viridis_c(option = "A")
}
)
```

```{r}
lapply(doc_topics, function(x) { 
  x |>
    gather_topic_prob() |>
    join_y() |>
    mutate(luokka = if_else(suht_muutos_2010_2022 > 0, "Kasvava", "Taantuva"),
           topic = factor(as.integer(topic))) |>
    summarise(mean_prop = mean(prop), .by = c(luokka, topic)) |>
    tidyr::pivot_wider(names_from = luokka, values_from = mean_prop) |>
    mutate(diff = Kasvava-Taantuva) |>
    tidyr::pivot_longer(Kasvava:Taantuva, names_to = "luokka", values_to = "prop") |>
    ggplot() +
    geom_tile(aes(x = topic, y = luokka, fill = diff)) +
    scale_fill_distiller(palette = "Spectral")
})
```

```{r}
titles <- aspol |> 
  group_by(kunta) |> 
  slice_head(n=10) |> 
  summarise(title = paste(FORM, collapse = " ")) |>
  inner_join(taantuvat)
titles
```

```{r}
titles_per_topics <- lapply(doc_topics, function(x) {
  gather_topic_prob(x) |>
    slice_max(order_by = prop, n = 1, by = doc_id) |>
    left_join(titles, by = join_by("doc_id" == "kunta"))
  })
titles_per_topics
```

```{r, rows.print=16, }
titles_per_topics$k_5 |>
  filter(topic==3) |>
  select(doc_id, title)
```


```{r}
doc_topics$k_5 |> convert(to = "data.frame") |>
  tidyr::pivot_longer(!doc_id, names_to = "topic", values_to = "prop") |>
  left_join(taantuvat, by = join_by("doc_id" == "kunta")) |>
  filter(!is.na(luokka)) |>
  group_by(luokka, topic) |>
  summarise(mean_prop = mean(prop)) |>
  ggplot() +
  geom_point(aes(x = topic, y = mean_prop, colour = luokka))
```


```{r}
doc_topics$k_5 |> convert(to = "data.frame") |>
  tidyr::pivot_longer(!doc_id, names_to = "topic", values_to = "prop") |>
  ggplot() +
  geom_col(aes(x = prop, y = topic))
```

