---
title: "4 Key terms based on LDA"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
library(rfinstats)
library(dplyr)
library(sf)
library(tidytext)
library(ggplot2)
library(stringr)
library(forcats)
```

```{r}
avainsanat_1_2 <- c("kanta#kaupunki", "vyöhyke", "kaupunki#rakenne", "luonto", 
                    "joukko#liikenne", "asumis#oikeus#asunto", "kaupungin#osa",
                    "väestön#kasvu", "maa#poliittinen", "täydennys#rakentaminen",
                    "asunto#osake#yhtiö", "huone", "vakituinen", "nainen", "kunto",
                    "tuntematon", "laina", "myynti", "kiinteistö", "koti#hoito",
                    "myydä")
avainsanat_2_3 <- c("laitos#hoito", "tehostettu", "kehitys#vammainen", "itsenäinen",
                    "ikä#ihminen", "vähetä", "tavallinen", "perus#korjaus", "ikääntyvä",
                    "maan#käyttö", "täydennys#rakentaminen", "maa#poliitinen",
                    "kaupungin#osa", "väestön#kasvu", "asumis#oikeus#asunto",
                    "joukko#liikenne", "luonto", "kaupunki#rakenne", "vyöhyke",
                    "kanta#kaupunki")
avainsanat_1_3 <- c("laitoshoito", "tehostettu", "kehitysvammainen", "itsenäinen",
                    "ikä#ihminen", "vähetä", "ikääntyvä", "kanta#kaupunki", "tavallinen",
                    "periaate", "tuntematon", "laina", "vakituinen", "kustannus",
                    "Rivi", "asunto#osake#yhtiö", "kunta", "kiinteistö", "myynti",
                    "myydä")
```


```{r}
filter_key_lemma <- function(df, key_terms) {
  df |> filter(LEMMA %in% key_terms)
}
```

```{r}
filter_municipality <- function(df) {
  suppressMessages(
    df |> inner_join(taantuvat)
  )
}
```

```{r}
calc_lemma_prop <- function(df, group) {
  lemma_total <- df |> count(LEMMA, name = "tf")
  lemma_luokka <- df |> count(LEMMA, {{group}}, name = "dtf")
  
  suppressMessages(
    left_join(lemma_total, lemma_luokka) |>
      mutate(osuus = dtf / tf)
  )
  
}
```

```{r}
plot_lemma_prop <- function(df, x, group) {
    ggplot(df) +
      geom_col(aes(x = {{x}}, y = LEMMA, fill = {{group}}), position = "fill")
}
```


```{r}
lapply(list(avainsanat_1_2, avainsanat_2_3, avainsanat_1_3), function(x) {
  aspol_filtered |>
    filter_municipality() |>
    filter_key_lemma(x) |>
    calc_lemma_prop(luokka) |>
    plot_lemma_prop(osuus, luokka)
})
```

