---
title: "5 Tidytext format"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
# devtools::install_github("StranMax/rfinstats")
library(rfinstats)
library(dplyr)
library(tidytext)
library(ggplot2)
library(stringr)
library(forcats)
```

```{r}
plot_max_terms <- function(df, .by, .n) {
  df |>
    slice_max(order_by = {{.by}}, n = {{.n}}) |>
    ggplot() +
    geom_col(aes(x = n, y = reorder(LEMMA, n), fill = UPOSTAG)) +
    scale_x_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE))
}
```


```{r}
aspol |>
  count(LEMMA, UPOSTAG, sort = TRUE) |>
  plot_max_terms(.by = n, .n = 20)
```

```{r}
aspol_filtered |>
  count(LEMMA, UPOSTAG, sort = TRUE) |>
  plot_max_terms(.by = n, .n = 20)
```

```{r}
count_doc_size <- function(df, group) {
  group_size <- df |> count({{group}}, name = "group_term_count")
  
  suppressMessages(
  df |>
    count({{group}}, LEMMA, sort = TRUE, name = "dtc") |>
    left_join(group_size)
  )
}
```


```{r}
tidy_tf_idf <- aspol_filtered |>
  inner_join(taantuvat) |>
  count_doc_size(luokka) |>
  bind_tf_idf(LEMMA, luokka, dtc)
```

```{r}
tidy_tf_idf %>%
  select(-group_term_count) %>%
  arrange(desc(tf_idf))
```

```{r}
tidy_tf_idf %>%
  group_by(luokka) %>%
  slice_max(tf_idf, n = 10) %>%
  ungroup() %>%
  ggplot(aes(tf_idf, fct_reorder(LEMMA, tf_idf), fill = luokka)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~luokka, ncol = 2, scales = "free") +
  labs(x = "tf-idf", y = NULL)
```

```{r, message=FALSE, warning=FALSE}
library(widyr)
```

```{r}
kappaleet <- aspol_filtered |>
  mutate(kappale = paste0(kunta, "-", sent)) |>
  count(kappale, LEMMA)
```

```{r}
word_pairs <- kappaleet |>
  pairwise_count(LEMMA, kappale, sort = TRUE, upper = FALSE)

word_pairs
```

```{r}
word_cors <- kappaleet %>%
  group_by(LEMMA) %>%
  filter(n() >= 40) %>%
  pairwise_cor(LEMMA, kappale, sort = TRUE, upper = FALSE)

word_cors |> print(n = 50)
```

```{r}
word_cors |>
  mutate(sanapari = paste0(item1, " <-> ", item2)) |>
  slice_max(correlation, n = 20) |>
ggplot() +
  geom_col(aes(x = correlation, y = fct_reorder(sanapari, correlation)))
```

```{r}
kappaleet_kunta <- aspol_filtered |>
  count(kunta, LEMMA)
```

```{r}
word_pairs_kunta <- kappaleet_kunta |>
  pairwise_count(LEMMA, kunta, sort = TRUE, upper = FALSE)

word_pairs_kunta
```

```{r}
word_cors_kunta <- kappaleet_kunta %>%
  group_by(LEMMA) %>%
  filter(n() >= 40) %>%
  pairwise_cor(LEMMA, kunta, sort = TRUE, upper = FALSE)

word_cors_kunta
```

```{r}
word_cors_kunta |>
  mutate(sanapari = paste0(item1, " <-> ", item2)) |>
  slice_max(correlation, n = 20) |>
ggplot() +
  geom_col(aes(x = correlation, y = fct_reorder(sanapari, correlation)))
```

