---
title: "6 Word clouds"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
# devtools::install_github("StranMax/rfinstats")
library(rfinstats)
library(dplyr)
library(tidytext)
library(ggplot2)
library(stringr)
library(forcats)
library(ggwordcloud)
```

```{r}
aspol_f <- inner_join(preprocess_corpus(aspol), taantuvat)
```

```{r}
count_doc_size <- function(df, group) {
  group_size <- df |> count({{group}}, name = "group_term_count")
  
  suppressMessages(
  df |>
    count({{group}}, LEMMA, sort = TRUE, name = "dtc") |>
    left_join(group_size)
  )
}
```

```{r}
tidy_tf_idf <- aspol_f |>
  count_doc_size(luokka) |>
  bind_tf_idf(LEMMA, luokka, dtc)
```

```{r}
tidy_tf_idf %>%
  select(-group_term_count) %>%
  arrange(desc(tf_idf))
```

```{r, fig.width=8.27, fig.height=5.83, fig.fullwidth=TRUE}
tidy_tf_idf |>
  slice_max(tf_idf, n = 30, by = luokka) |>
ggplot(aes(label = LEMMA, size = tf_idf, colour = luokka)) +
  geom_text_wordcloud_area(rm_outside = TRUE, shape = "square", use_richtext = FALSE) +
  scale_size_area(max_size = 30) +
  theme_minimal() +
  facet_wrap(~luokka, nrow = 2)
```

