---
title: "Document term matrix"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Converting tidytext format to numerical matrix form.

```{r setup, message=FALSE, warning=FALSE}
library(rfintext)
# devtools::install_github("StranMax/rfinstats")
library(rfinstats)
library(sf)
library(quanteda)
library(tidytext)
library(stringr)
library(dplyr)
library(readr)
```


```{r}
aspol_filtered <- aspol |> 
  add_count(kunta, LEMMA, name = "kunta_lemma") |> 
  add_count(LEMMA, name = "lemma") |> 
  filter(
    lemma > kunta_lemma,  # Termi pitää esiintyä vähintään kahdessa eri dokumentissa
         lemma > 10,  # Pitää esiintyä yhteensä yli 10 kertaa (voi olla ehkä isompikin)
         UPOSTAG %in% c("NOUN", "VERB", "ADJ"),  # Substantiivit, verbit ja adjektiivit
         nchar(FORM) > 1,  # Yksittäiset merkit pois
         nchar(LEMMA) > 1,  # Yksittäiset merkit pois
         !str_detect(FEATS, "Abbr=Yes|NumType=Ord")  # Lyhenteet ja järjestysnumerot (adj) pois
         )  

lemma <- aspol_filtered |>
  count(kunta, LEMMA, name = "dtf") |>
  bind_tf_idf(LEMMA, kunta, dtf)
```

Let's create variable `y` we are trying to explain with word frequencies.

```{r}
taantuvat <- taantuvat
y <- taantuvat[c("kunta", "suht_muutos_2010_2022")] |>
  inner_join(lemma[c("kunta")]) |>
  group_by(kunta) |>
  slice(1)
```

We create data with only those docs we have y value

```{r}
data <- left_join(lemma, y) |>
  filter(!is.na(LEMMA), !is.na(suht_muutos_2010_2022)) |>
  select(kunta, LEMMA, dtf, tf, tf_idf, suht_muutos_2010_2022)

stopifnot(y$kunta_nimi == unique(data$kunta))
```

```{r}
n <- cast_dfm(data = data, document = kunta, term = LEMMA, value = dtf) 
tf <- cast_dfm(data = data, document = kunta, term = LEMMA, value = tf)
tf_idf <- cast_dfm(data = data, document = kunta, term = LEMMA, value = tf_idf)
```


We save 4 objects:

1. ID_labels (kunnat)  
2. Feature_names (LEMMA)  
3. Data (doc-term-matrix)  
4. y-variable (väkiluvun muutos)

```{r}
save_data <- function(X, y, dir_out = tempdir()) {
  
  id_label <-  X |> as.matrix() |> row.names()
  readr::write_lines(id_label, file.path(dir_out, "id_label.txt"), sep = ";")
  
  feature_name <- X |> as.matrix() |> colnames()
  readr::write_lines(feature_name, file.path(dir_out, "feature_name.txt"), sep = ";")
  
  data <- X |> as.matrix() |> as.data.frame()
  readr::write_csv(data, file.path(dir_out, "data.csv"))
  
  label <- y$suht_muutos_2010_2022
  readr::write_lines(label, file.path(dir_out, "label.txt"), sep = ";")
  
  unlink(dir_out)
}
```


```{r}
# save_data(n, y, dir_out = "C:/Users/maxs/Documents/data/aspol_scikit-learn/n")
# save_data(tf, y, dir_out = "C:/Users/maxs/Documents/data/aspol_scikit-learn/tf")
# save_data(tf_idf, y, dir_out = "C:/Users/maxs/Documents/data/aspol_scikit-learn/tf_idf")
```

